### ISSUE TITLE
Is there any easy way to get the image to render un-tilted?

### ISSUE THREAD

**Issue by michaelwhelehan** [cbnolok/ReMapRenderer#1]
Hi there :)

I came across this nice tool you built and I'm trying to get the map blocks to render at a 90 degree angle so that I can make map tiles to load into Leaflet and view them in a web browser like Google maps.

Been trying to get my head around everything for the past 4 days tinkering with things but I just can't for the life of me figure out how to rotate the image and get it to have equal width and height for the tiles that have Z coords.

Any help would be greatly appreciated!

Kind Regards
Michael

**Comment by cbnolok** [comment]
I don't think i understood what's the exact result you want to achieve, in any case i did not write the rendering part so i fear i can be of little help on that

**Comment by michaelwhelehan** [comment]
@cbnolok thanks for the response, I will close as I managed to figure it out
